Vagrant.configure("2") do |config|

  config.vm.define "legacy-web" do |web|
    web.vm.box = "generic/rocky8"
    web.vm.hostname = "legacy-web"
    web.vm.network "private_network", ip: "192.168.232.11"
    web.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
    end
  end

  config.vm.define "legacy-was" do |was|
    was.vm.box = "generic/rocky8"
    was.vm.hostname = "legacy-was"
    was.vm.network "private_network", ip: "192.168.232.12"
    was.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
    end
  end

  config.vm.define "legacy-zabbix" do |zbx|
    zbx.vm.box = "generic/rocky8"
    zbx.vm.hostname = "legacy-zabbix"
    zbx.vm.network "private_network", ip: "192.168.232.13"
    zbx.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
    end
  end

end